/**
 * Build script that bundles Atlas data into data/atlas-data.json for the MCP server.
 *
 * This file generates a build artifact — it is NOT source. The output is git-ignored
 * (see mcp/.gitignore), regenerated by `npm run build:data`, shipped in the npm package
 * via package.json "files", and rebuilt on `prepublishOnly` and in CI.
 *
 * Purpose: give AI agents the canonical HTML snippets they need to assemble Atlas pages.
 * The server is for building HTML — not for authoring CSS or merely suggesting class names.
 *
 * atlas-data.json schema (minified JSON):
 *   {
 *     components: [{ name, title, description, classPrefixes, examples: Example[] }],
 *     patterns:   [{ name, title, description, examples: Example[] }],  // page-level compositions
 *     atomics:    [{ name, title, description, examples: Example[] }],
 *     classNames: { [name]: ClassInfo },  // supporting metadata, not the primary product
 *     tokens:     { ... },                // supporting metadata
 *     generatedAt: string                 // ISO timestamp
 *   }
 *   Example = { title: string, language: 'html', code: string }
 *
 * Only HTML code fences are captured as examples (html, abut-html, html-no-indent,
 * html-no-example), all normalized to language 'html'. CSS/SCSS fences are intentionally
 * excluded. Each example records the nearest preceding markdown heading as its `title`,
 * so agents can request a snippet by intent (e.g. the "Testimonial card").
 */

import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import fm from 'front-matter';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const CSS_DIST = join(__dirname, '../../css/dist');
const SITE_SRC = join(__dirname, '../../site/src');
const OUTPUT_DIR = join(__dirname, '../data');

// Atlas HTML code fences. All are normalized to 'html' in the output.
const HTML_FENCES = new Set(['html', 'abut-html', 'html-no-indent', 'html-no-example']);

/**
 * Extract canonical HTML snippets from a markdown document, in document order.
 * Each snippet is tagged with the nearest preceding heading so it can be requested by intent.
 * CSS/SCSS and other non-HTML fences are ignored — the goal is building HTML pages.
 */
function extractCodeExamples(content) {
	const examples = [];
	// Match either an ATX heading line or a fenced code block, in document order.
	const tokenRegex = /^(#{1,6})\s+(.+?)\s*$|```(\w[\w-]*)?\r?\n([\s\S]*?)```/gm;
	let currentHeading = '';
	let match;

	while ((match = tokenRegex.exec(content)) !== null) {
		if (match[1]) {
			currentHeading = match[2].trim();
			continue;
		}

		const language = (match[3] || 'html').toLowerCase();
		if (!HTML_FENCES.has(language)) continue;

		const code = match[4].trim();
		if (code.length <= 10) continue;

		examples.push({ title: currentHeading, language: 'html', code });
	}

	return examples;
}

function parseMarkdownDoc(filePath) {
	const content = readFileSync(filePath, 'utf-8');
	const parsed = fm(content);
	return {
		frontmatter: parsed.attributes,
		content: parsed.body
	};
}

function loadComponents() {
	const componentsDir = join(SITE_SRC, 'components');
	if (!existsSync(componentsDir)) {
		console.warn('Components directory not found');
		return [];
	}

	const files = readdirSync(componentsDir).filter(f => f.endsWith('.md') && f !== 'overview.md');
	return files.map(file => {
		const filePath = join(componentsDir, file);
		const { frontmatter, content } = parseMarkdownDoc(filePath);
		const name = file.replace('.md', '');

		return {
			name,
			title: frontmatter.title || name,
			description: frontmatter.description || '',
			classPrefixes: frontmatter.classPrefixes || [name],
			examples: extractCodeExamples(content)
		};
	});
}

function loadAtomics() {
	const atomicsDir = join(SITE_SRC, 'atomics');
	if (!existsSync(atomicsDir)) {
		console.warn('Atomics directory not found');
		return [];
	}

	const files = readdirSync(atomicsDir).filter(f => f.endsWith('.md') && f !== 'overview.md');
	return files.map(file => {
		const filePath = join(atomicsDir, file);
		const { frontmatter, content } = parseMarkdownDoc(filePath);
		const name = file.replace('.md', '');

		return {
			name,
			title: frontmatter.title || name,
			description: frontmatter.description || '',
			examples: extractCodeExamples(content)
		};
	});
}

function loadPatterns() {
	const patternsDir = join(SITE_SRC, 'patterns');
	if (!existsSync(patternsDir)) {
		console.warn('Patterns directory not found');
		return [];
	}

	const files = readdirSync(patternsDir).filter(f => f.endsWith('.md') && f !== 'overview.md');
	return files.map(file => {
		const filePath = join(patternsDir, file);
		const { frontmatter, content } = parseMarkdownDoc(filePath);
		const name = file.replace('.md', '');

		return {
			name,
			title: frontmatter.title || name,
			description: frontmatter.description || '',
			examples: extractCodeExamples(content)
		};
	});
}

function main() {
	console.log('Building Atlas MCP data...');

	// Load class names
	const classNamesPath = join(CSS_DIST, 'class-names.json');
	if (!existsSync(classNamesPath)) {
		throw new Error(`class-names.json not found. Run 'npm run build:class-names' first.`);
	}
	const classNames = JSON.parse(readFileSync(classNamesPath, 'utf-8'));
	console.log(`  Loaded ${Object.keys(classNames).length} class names`);

	// Load tokens
	const tokensPath = join(CSS_DIST, 'tokens.json');
	if (!existsSync(tokensPath)) {
		throw new Error(`tokens.json not found. Run 'npm run build:tokens' first.`);
	}
	const tokens = JSON.parse(readFileSync(tokensPath, 'utf-8'));
	console.log(`  Loaded tokens`);

	// Load components
	const components = loadComponents();
	console.log(`  Loaded ${components.length} components`);

	// Load atomics
	const atomics = loadAtomics();
	console.log(`  Loaded ${atomics.length} atomic categories`);

	// Load patterns (page-level, multi-component HTML compositions)
	const patterns = loadPatterns();
	console.log(`  Loaded ${patterns.length} patterns`);

	// Bundle all data. HTML-snippet sources first; class/token metadata is supporting data.
	const atlasData = {
		components,
		patterns,
		atomics,
		classNames,
		tokens,
		generatedAt: new Date().toISOString()
	};

	// Write output
	if (!existsSync(OUTPUT_DIR)) {
		mkdirSync(OUTPUT_DIR, { recursive: true });
	}

	const outputPath = join(OUTPUT_DIR, 'atlas-data.json');
	writeFileSync(outputPath, JSON.stringify(atlasData));
	console.log(`  Written to ${outputPath}`);
	console.log('Done!');
}

main();
