import type { LocalPageConfig } from './typings';

export const pages: LocalPageConfig[] = [
	{ pathname: '/index.html', name: 'Home', themes: ['light'] },
	{ pathname: '/atomics/border.html', name: 'Atomics/border', themes: ['light'] },
	{ pathname: '/atomics/display.html', name: 'Atomics/display', themes: ['light'] },
	{ pathname: '/atomics/flex.html', name: 'Atomics/flex', themes: ['light'] },
	{ pathname: '/atomics/image.html', name: 'Atomics/image', themes: ['light'] },
	{ pathname: '/atomics/line-html.html', name: 'Atomics/line', themes: ['light'] },
	{ pathname: '/atomics/lists.html', name: 'Atomics/lists', themes: ['light'] },
	{ pathname: '/atomics/overflow.html', name: 'Atomics/overflow', themes: ['light'] },
	{ pathname: '/atomics/overview.html', name: 'Atomics/overview', themes: ['light'] },
	{ pathname: '/atomics/position.html', name: 'Atomics/position', themes: ['light'] },
	{ pathname: '/atomics/shadow.html', name: 'Atomics/shadow', themes: ['light'] },
	{ pathname: '/atomics/spacing.html', name: 'Atomics/spacing', themes: ['light'] },
	{ pathname: '/atomics/typography.html', name: 'Atomics/typography', themes: ['light'] },
	{ pathname: '/atomics/width.html', name: 'Atomics/width', themes: ['light'] },
	{ pathname: '/components/breadcrumbs.html', name: 'Components/breadcrumbs', themes: ['light'] },
	{ pathname: '/components/button.html', name: 'Components/button', themes: ['light'] },
	{ pathname: '/components/checkbox.html', name: 'Components/checkbox', themes: ['light'] },
	{ pathname: '/components/help.html', name: 'Components/help', themes: ['light'] },
	{ pathname: '/components/icon.html', name: 'Components/icon', themes: ['light'] },
	{ pathname: '/components/input.html', name: 'Components/input', themes: ['light'] },
	{ pathname: '/components/label.html', name: 'Components/label', themes: ['light'] },
	{ pathname: '/components/link-button.html', name: 'Components/link-button', themes: ['light'] },
	{ pathname: '/components/markdown.html', name: 'Components/markdown', themes: ['light'] },
	{ pathname: '/components/overview.html', name: 'Components/overview', themes: ['light'] },
	{ pathname: '/components/popover.html', name: 'Components/popover', themes: ['light'] },
	{ pathname: '/components/radio.html', name: 'Components/radio', themes: ['light'] },
	{ pathname: '/components/scroll.html', name: 'Components/scroll', themes: ['light'] },
	{ pathname: '/components/select.html', name: 'Components/select', themes: ['light'] },
	{ pathname: '/components/table.html', name: 'Components/table', themes: ['light'] },
	{ pathname: '/components/textarea.html', name: 'Components/textarea', themes: ['light'] },
	{ pathname: '/components/toggle.html', name: 'Components/toggle', themes: ['light'] },
	{ pathname: 'patterns/article-header.html', name: 'Patterns/article-header', themes: ['light'] }
];
