# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pr: none

pool:
  vmImage: vs2017-win2016

steps:
  - task: NodeTool@0
    displayName: Use node 16.6.x
    inputs:
      versionSpec: '16.6.x'

  - script: npm ci --no-optional
    displayName: Install

  - script: npm run lint
    displayName: Lint

  - script: npm run build:site
    displayName: Build site

  - task: AzureFileCopy@4
    displayName: Deploy site
    inputs:
      sourcePath: $(System.DefaultWorkingDirectory)/site/dist/*
      azureSubscription: 'MSFTDOCS - AtlasDesign Content Publisher'
      destination: azureBlob
      storage: atlasdesignpublic
      containerName: $web

  - task: ComponentGovernanceComponentDetection@0
    displayName: Component Governance Detection
    inputs:
      alertWarningLevel: 'High'
