# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: Pull Request

trigger: none

pr:
  autoCancel: true
  drafts: true

pool:
  vmImage: windows-2022

# Issues? Check out
# windows-latest included software: https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md
steps:
  - task: NodeTool@0
    displayName: Use node 16.13.x
    inputs:
      versionSpec: '16.13.x'

  - script: npm -v
    displayName: View NPM Version

  - script: npm ci
    displayName: Install

  - script: npm run lint
    displayName: Lint

  - script: npm run build:site -- -- --dist-dir "dist/pulls/$(System.PullRequest.PullRequestNumber)" --public-url "/pulls/$(System.PullRequest.PullRequestNumber)/"
    displayName: Build site

  - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
    inputs:
      BuildDropPath: '$(System.DefaultWorkingDirectory)' # generating a manifest that contains all dependencies, not just what is included in the deployed bundles
    displayName: 'Generate SBOM'

  - task: PublishBuildArtifacts@1
    condition: succeeded()
    inputs:
      ArtifactName: _manifest
      ArtifactType: Container
      PathtoPublish: $(System.DefaultWorkingDirectory)/_manifest
    displayName: Publish SBOM

  - task: AzureFileCopy@4
    displayName: Deploy site
    inputs:
      sourcePath: $(System.DefaultWorkingDirectory)/site/dist/*
      azureSubscription: 'MSFTDOCS - AtlasDesign Content Publisher'
      destination: azureBlob
      storage: atlasdesignpublic
      containerName: $web

  - task: ComponentGovernanceComponentDetection@0
    displayName: Component Governance Detection
    inputs:
      alertWarningLevel: 'High'
