name: Release

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    if: github.repository == 'microsoft/atlas-design'
    permissions:
      contents: write # to create release (changesets/action)
      pull-requests: write # to create pull request (changesets/action)
    name: Release
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # https://github.com/changesets/action
      - name: Create or update Changesets version PR
        uses: changesets/action@v1
        env:
          HOME: ${{ github.workspace }} # https://github.com/changesets/action/issues/147
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB }}
